### ISSUE TITLE
Redundant lines in Docker file

### ISSUE THREAD

**Issue by MuellerSeb** [kinow/docker#2]
https://github.com/kinow/docker/blob/a9886f922b7af4f2152f4b7fb9f9ee87b11b5e1e/mhm-fdb/Dockerfile#LL160C1-L161C19

These lines are redundant
```
    git==2.40.1 \
    python==3.10 \
```

**Comment by kinow** [comment]
Oh, copy-pasta bug, fixing it. Thanks @MuellerSeb !
